### ISSUE TITLE
建议提交至micsoft edge扩展商店

### ISSUE THREAD

**Issue by wiki6** [YMFE/cross-request#14]
国内开发人员使用更加方便

**Comment by chinaxiaoyh** [comment]
的确 慢慢开始转edge了

**Comment by codefalse** [comment]
最近提交到Edge了：https://microsoftedge.microsoft.com/addons/detail/crossrequest/bephiepmhphdlafkfonngafenjhfehlb

**Comment by wiki6** [comment]
正常可用，感谢 codefalse
